# Generated by Django 4.1.1 on 2022-09-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_categoryproduct_measure_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="category_product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.categoryproduct",
                verbose_name="Category product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.categoryproduct",
                verbose_name="Category product",
            ),
        ),
    ]
